# This workflow will:
# - compile and sign project on linux with JDK 17
# - run sonar on linux
# - deploy snapshot on maven

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      JDK_VERSION: 17

    steps:
     - name: Checkout
       uses: actions/checkout@v4.1.1
       with:
         fetch-depth: 0

     - name: Cache
       uses: actions/cache@v3.3.2
       with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('pom.xml') }}

     - name: Maven
       uses: stCarolas/setup-maven@v4.5
       with:
         maven-version: 3.9.6

     - name: Set JDK
       uses: actions/setup-java@v4.0.0
       with:
         java-version: |
           17
         distribution: 'temurin'
         mvn-toolchain-id: |
           JavaSE-17
         server-id: ossrh
         server-username: MAVEN_USERNAME
         server-password: MAVEN_PASSWORD

     - name: Import GPG key
       uses: crazy-max/ghaction-import-gpg@v6.0.0
       with:
         gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
         passphrase: ${{ secrets.GPG_PASSPHRASE }}

     - name: Compile
       run: mvn clean deploy -U -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} -Psign
       env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

  sonar:
    runs-on: ubuntu-latest
    env:
      JDK_VERSION: 17

    steps:
     - name: Checkout
       uses: actions/checkout@v4.1.1
       with:
         fetch-depth: 0

     - name: Cache
       uses: actions/cache@v3.3.2
       with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('pom.xml') }}

     - name: Maven
       uses: stCarolas/setup-maven@v4.5
       with:
         maven-version: 3.9.6

     - name: Set JDK
       uses: actions/setup-java@v4.0.0
       with:
         java-version: |
           17
         distribution: 'temurin'
         mvn-toolchain-id: |
           JavaSE-17

     - name: Compile
       run: mvn clean org.sonarsource.scanner.maven:sonar-maven-plugin:sonar verify -U -Dsonar.organization=b3dgs -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=b3dgs_b3dgs-parent
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
